### ISSUE TITLE
Can't drag green box to console

### ISSUE THREAD

**Issue by duartecosta21** [nakano000/Resolve_Script#18]
I followed this tutorial: https://www.youtube.com/watch?v=HV3IsJ7VAwE&t=0s

In the part where I need to drag the green bix to the console nothing happens, I even dragged it to a note pad, got the code, pasted in the console, seemed to work but the functions didn't show up.

I tried on both DR 18.6 and 19 BETA

**Comment by LorenzoWhite** [comment]
Seconded. Not sure what the green box contains, so I don't know what to paste into the console

**Comment by nakano000** [comment]
Main Menu > Fusion > Fusion Settings
Adding $(RS_FUSION_USER_PATH) to UserPaths: in "Path Map".

example
User data:;All data:;Fusion:;$(RS_FUSION_USER_PATH)

**Comment by ShuichiroTsuda** [comment]
Davinci Resolve 19.1.1
macOS Sonoma 14.5

I might be slightly off-topic, but I’m experiencing the same situation as @duartecosta21 .
In my case, it seems that the virtual environment created with `setup_python.command` is not being referenced.

The path configured in Main Menu > Fusion > Fusion Settings seems correct.
<img width="580" alt="image" src="https://github.com/user-attachments/assets/dbb07b88-dbd5-479e-9fce-ad224dff7d55" />

However, when I click Tatie (or any other script), nothing happens. Checking the console output reveals the following:
```
Global.Paths.Map.UserPaths: UserData:;AllData:;Fusion:;$(RS_FUSION_USER_PATH)
Lua> 
Traceback (most recent call last):
  File "/Users/***/Projects/Resolve_Script2.5.12_mac/app/fusion/UserPath/Scripts/Comp/RS/Tatie.py3", line 1, in <module>
    from rs_fusion.tool.tatie import run
  File "/Users/***/Projects/Resolve_Script2.5.12_mac/app/fusion/python/rs_fusion/tool/tatie/__init__.py", line 1, in <module>
    from .tatie import (
        run,
    )
  File "/Users/***/Projects/Resolve_Script2.5.12_mac/app/fusion/python/rs_fusion/tool/tatie/tatie.py", line 7, in <module>
    from PySide6.QtCore import (
        Qt,
    )
ModuleNotFoundError: No module named 'PySide6'
```

I checked the Python version being used in the console, and here are the results:
```
Py3> import sys
Py3> print(sys.version)
3.13.1 (main, Dec  3 2024, 17:59:52) [Clang 16.0.0 (clang-1600.0.26.4)]
Py3> print(sys.executable)
/Applications/DaVinci Resolve/DaVinci Resolve.app/Contents/MacOS/Resolve

```

What should I check and how can I fix this?

**Comment by depressed-pho** [comment]
＠ShuichiroTsuda: Are you sure you launched Resolve via the resolve launcher? To me that sounds like an issue that happen when it's launched via Dock or Finder.

**Comment by depressed-pho** [comment]
Not sure this is the same issue as the OP is talking about, but on macOS I have an issue wrt. the green box thing. On this platform the Fusion console window is only shown when the application is focused. As soon as it loses focus the console window disappears, which makes it impossible to drag the green box onto it. I could work around the issue by opening the Fusion settings and manually appending `$(RS_FUSION_USER_PATH)` to `UserPaths:`.
