### ISSUE TITLE
[Bug // 19.0.1 - 2.5.11] Import via PSD Splitter Not Importing, Throwing Errors in Console

### ISSUE THREAD

**Issue by FocalFlare** [nakano000/Resolve_Script#20]
# Technical Info
### DaVinci Resolve
- License: Free
- Version: 19.0.1

### Script version
2.5.11

### Issue
_Splitting the PSD project file I'm trying to use works without any flaws whatsoever, but when I try to import the PSD into Fusion via the generated JSON file, it does nothing and instead throws the error provided at the bottom._

_Keep in mind that this is my second time trying to use these scripts so I may be missing something crucial here which might not seem obvious to me! Also, I have this set to English because I monolingually do not understand Japanese (I know a complete English translation is planned, though), so we're both learning together if anything is confusing between us in this issue._

**_Solutions for this error might work for everyone with this issue but are 100% not guaranteed to work for those with even a slightly different issue. Regardless, I appreciate your input(s)!_**

# Other Info
### Output error
```
Traceback (most recent call last):
  File "E:\Docs and stuff\DaVinci Resolve\3rd-party Plug-ins and Tools\Resolve_Script2.5.11_win\app\fusion\python\rs_fusion\tool\importer\importer.py", line 562, in import_json
    importer.make()
  File "E:\Docs and stuff\DaVinci Resolve\3rd-party Plug-ins and Tools\Resolve_Script2.5.11_win\app\fusion\python\rs_fusion\tool\importer\importer.py", line 468, in make
    xf, _, _uc, name_list = self.add_node_B(
  File "E:\Docs and stuff\DaVinci Resolve\3rd-party Plug-ins and Tools\Resolve_Script2.5.11_win\app\fusion\python\rs_fusion\tool\importer\importer.py", line 293, in add_node_B
    xf, bg = self.add_xf_bg(pos_x, pos_y, name)
  File "E:\Docs and stuff\DaVinci Resolve\3rd-party Plug-ins and Tools\Resolve_Script2.5.11_win\app\fusion\python\rs_fusion\tool\importer\importer.py", line 152, in add_xf_bg
    xf.SetAttrs({'TOOLS_Name': name})
AttributeError: 'NoneType' object has no attribute 'SetAttrs'
```

### PSD project file
[conceptualizing a YT overlay base-pdn but PSD script without groups with rasterized layers.zip](https://github.com/user-attachments/files/17449012/conceptualizing.a.YT.overlay.base-pdn.but.PSD.script.without.groups.with.rasterized.layers.zip)

### PSD Splitter (export and import) settings
![image](https://github.com/user-attachments/assets/09f2fd6d-39c3-4751-bd5e-003f851f418e)
![image](https://github.com/user-attachments/assets/056d8509-99b0-473e-9965-6a017541c2bc)
![image](https://github.com/user-attachments/assets/8f87104b-b54d-4296-884c-2b3d894bcf7b)
![image](https://github.com/user-attachments/assets/c94b0893-091f-4513-a57f-5f4f7bc25663)

**Comment by FocalFlare** [comment]
_@nakano000 (or anyone else) reopen this issue if you still have any ideas or suggestions on why this is happening. This issue will be closed as not planned due to there being no response for at least 2 months._
